services:
  - type: web
    name: backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run.py"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production

  - type: static
    name: frontend
    staticPublishPath: /app/static
    buildCommand: "npm install && npm run build"
    plan: free
